bin.includes = META-INF/,\
               about.ini,\
               about.html,\
               about.mappings,\
               about.properties,\
               eclipse_lg.png,\
               eclipse_lg@2x.png,\
               org.eclipse.ui.intro.universal.solstice/,\
               plugin_customization.ini,\
               plugin.xml,\
               plugin.properties,\
               epp32.png,\
               ruyisdk16.png,\
               ruyisdk16@2x.png,\
               ruyisdk256.png,\
               ruyisdk256@2x.png,\
               ruyisdk32.png,\
               ruyisdk32@2x.png,\
               ruyisdk48.png,\
               ruyisdk48@2x.png,\
               intro-ruyisdk.svg
